language: haskell
sudo: false
addons:
  apt:
    sources: hvr-ghc
    packages:
      - cabal-install-1.24
      - ghc-8.0.2
      - happy

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc

env:
  - GHCVER=8.0.2 CABAL=cabal-1.24

before_install:
  - export PATH=/opt/ghc/$GHCVER/bin:$PATH
  - cabal --version
  - cabal update

install:
  - cabal install idris --only-dependencies
  - cabal install idris -j1
  - echo "Installing dependencies"; export PATH=$PATH:$HOME/.cabal/bin; ./install_dependencies.sh

script:
  - ~/.cabal/bin/idris --build http.ipkg
  - ~/.cabal/bin/idris --install http.ipkg
  - pushd examples/simple
  - ~/.cabal/bin/idris --build simple.ipkg
  - popd

before_cache:
  - find ~/.cabal/ -iname '*.log' -delete #we do not want to cache logs
  - rm -r ~/.cabal/share/x86_64-linux-ghc-*/idris-*/http/ #we do not want to cache http, because that's the thing we are testing
