language: haskell
sudo: false
addons:
  apt:
    sources: hvr-ghc
    packages:
      - cabal-install-1.22
      - ghc-7.10.1
      - happy
cache:
  directories:
    - ~/.cabal
    - ~/.ghc

env:
  - GHCVER=7.10.1 CABAL=cabal-1.22

before_install:
  - |
      export PATH=/opt/ghc/$GHCVER/bin:$PATH
  - $CABAL update

  # Update happy when building with GHC head
  - |
    if [ $GHCVER = "head" ] || [ $GHCVER = "7.8.4" ] || [ $GHCVER = "7.10.1" ]; then
      $CABAL install --constraint=transformers\ installed happy alex
      export PATH=$HOME/.cabal/bin:$PATH
    fi

install:
  - travis_wait $CABAL install -j idris &
  - sleep 1; #waiting for cabal to be spawned
  - while ps -Af | grep -v grep | grep -q $CABAL; do
      echo -n .;
      sleep 1;
    done #waiting for cabal to be terminated while doing dummyoutputs
  - echo "Installing dependencies"; ./install_dependencies.sh

before_script:
  - export PATH=$PATH:~/.cabal/bin

script:
  - idris --build http.ipkg
  - idris --install http.ipkg
  - pushd examples/simple
  - idris --build simple.ipkg
  - popd

notifications:
  irc:
    channels:
      - "irc.freenode.org#dagd"
    skip_join: false
    template:
      - "\x0313idris-http\x0f/\x0306%{branch}\x0f \x0314%{commit}\x0f %{message} \x0302\x1f%{build_url}\x0f"

before_cache:
  - find ~/.cabal/ -iname '*.log' -delete #we do not want to cache logs
